### ISSUE TITLE
  bro can you pleas eplease help me i have x230 and want to install mac os big sur! please

### ISSUE THREAD

**Issue by fisforfaheem** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore#10]
bro can you please please help me i have x230 and want to install mac os big sur! please

**Comment by CLAY-BIOS** [comment]
> bro can you please please help me i have x230 and want to install mac os big sur! please

I'm sorry.
As much as I'd like to help you, I don't have an X230.

**Comment by fisforfaheem** [comment]
Can you do something about it .. i mean if a let you control my lenovox230
though remote desktop...bro your help would be very very beneficial!!! my
lenovox230 is running catilina  already so you would have access to all
stuff! pelase think about it  :)

**Comment by fisforfaheem** [comment]
Thanks! hope to see a tutorial in a month for big sur

**Comment by dimka4996** [comment]
https://github.com/banhbaoxamlan/X230-Hackintosh
