### ISSUE TITLE
How to select correct Intel Wifi kext?

### ISSUE THREAD

**Issue by DatenRaten** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore#104]
Hello,

I just set up my boot USB and according to the readme I should select the correct Intel Wifi kext according to my system version.
In my case that would be Big Sur. However I can't find where to make this selection:
![image](https://raw.githubusercontent.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/master/picture/Intel-WiFi.png)
I opened config.plist with PlistEdit Pro, but I don't think I'm at the right place.

Could somebody be so kind and give me hint where to find this option. I'm very new to all this. Thanks!

**Comment by spurd0** [comment]
Please use [OpenCore Configurator](https://mackie100projects.altervista.org/opencore-configurator/), screenshots are from it.
Also, here is config for Bug Sur:

> 		
			<dict>
				<key>Arch</key>
				<string>x86_64</string>
				<key>BundlePath</key>
				<string>AirportItlwm-Monterey.kext</string>
				<key>Comment</key>
				<string>intel-WiFi-Monterey</string>
				<key>Enabled</key>
				<false/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/AirportItlwm</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>Arch</key>
				<string>x86_64</string>
				<key>BundlePath</key>
				<string>AirportItlwm-Big-Sur.kext</string>
				<key>Comment</key>
				<string>intel-WiFi-Big-Sur</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/AirportItlwm</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>Arch</key>
				<string>x86_64</string>
				<key>BundlePath</key>
				<string>AirportItlwm-Catalina.kext</string>
				<key>Comment</key>
				<string>intel-WiFi-Catalina</string>
				<key>Enabled</key>
				<false/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/AirportItlwm</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>


You need:
>
			<key>Enabled</key>
			<true/>

**Comment by DatenRaten** [comment]
Thank you for the detailed response. I got everything up and running.
