### ISSUE TITLE
question regarding boot-args

### ISSUE THREAD

**Issue by step21** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore#125]
Hey,

thank you very much for sharing your work.
One question in the boot-args, what do `-iosd3v3` and `-carbeta` do? I could not find any information with opencore documentation or google.

**Comment by CLAY-BIOS** [comment]
> 

These two parameters are about the card reader driver
-iosd3v3 drives the SD card at 3.3V. Reference:https://github.com/0xFireWolf/RealtekCardReader/issues/16
The -carbeta parameter is used to start the card reader driver in beta versions of the system.

**Comment by CLAY-BIOS** [comment]
> Hey,
> 
> thank you very much for sharing your work. One question in the boot-args, what do `-iosd3v3` and `-carbeta` do? I could not find any information with opencore documentation or google.

These two parameters are about the card reader driver
-iosd3v3 drives the SD card at 3.3V. Reference:https://github.com/0xFireWolf/RealtekCardReader/issues/16
The -carbeta parameter is used to start the card reader driver in beta versions of the system.

**Comment by step21** [comment]
Ok great. Thank you for clarifying.
