### ISSUE TITLE
OCS: No schema for DisableLinkeditJettison at 6 index, context <Quirks>!

### ISSUE THREAD

**Issue by gonav8** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore#7]
Hi,
I got error as per subject.
Opencore still continue booting up and run.

Any help to fix this error ?

**Comment by gonav8** [comment]
![IMG_20200920_100803](https://user-images.githubusercontent.com/69380083/93707069-13f24a00-fb2c-11ea-8815-db6ed765fdac.jpg)

**Comment by gonav8** [comment]
Done.
Fixed by changing with original Opencore 0.61 files.
With Catalina Intel wifi works seamless. 

[EFI_CLAY-BIOS.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore/files/5251462/EFI_CLAY-BIOS.zip)

**Comment by hellosds** [comment]
@gonav8 Thanks a lot.
